postgres:
  host: "127.0.0.1"
  port: 5432
  user: "postgres"
  password: "password"
  database: "WallStreetSheep"


market:
  front_addr: tcp://180.168.146.187:10131
  broker_id: "9999"
  investor_id: "123456"
  password: "password"
  flow_path: flow
  is_using_udp: false
  is_multicast: false

trade:
  front_addr: tcp://180.168.146.187:10130
  broker_id: "9999"
  investor_id: "123456"
  password: "password"
  flow_path: flow

strategy:
  backtest:
    - example
  simulate:
    - example
  live:
    - example