-- Active: 1722473306304@@127.0.0.1@5432@wallstreetsheep
CREATE DATABASE WallStreetSheep;

CREATE TABLE Market (
    TradingDay TEXT NOT NULL,
    -- reserve1 TEXT NOT NULL,
    ExchangeID TEXT NOT NULL,
    -- reserve2 TEXT NOT NULL,
    LastPrice DOUBLE PRECISION NOT NULL,
    PreSettlementPrice DOUBLE PRECISION NOT NULL,
    PreClosePrice DOUBLE PRECISION NOT NULL,
    PreOpenInterest DOUBLE PRECISION NOT NULL,
    OpenPrice DOUBLE PRECISION NOT NULL,
    HighestPrice DOUBLE PRECISION NOT NULL,
    LowestPrice DOUBLE PRECISION NOT NULL,
    Volume DOUBLE PRECISION NOT NULL,
    Turnover DOUBLE PRECISION NOT NULL,
    OpenInterest DOUBLE PRECISION NOT NULL,
    ClosePrice DOUBLE PRECISION NOT NULL,
    SettlementPrice DOUBLE PRECISION NOT NULL,
    UpperLimitPrice DOUBLE PRECISION NOT NULL,
    LowerLimitPrice DOUBLE PRECISION NOT NULL,
    PreDelta DOUBLE PRECISION NOT NULL,
    CurrDelta DOUBLE PRECISION NOT NULL,
    UpdateTime TEXT NOT NULL,
    UpdateMillisec INT NOT NULL,
    BidPrice1 DOUBLE PRECISION NOT NULL,
    BidVolume1 DOUBLE PRECISION NOT NULL,
    AskPrice1 DOUBLE PRECISION NOT NULL,
    AskVolume1 DOUBLE PRECISION NOT NULL,
    BidPrice2 DOUBLE PRECISION NOT NULL,
    BidVolume2 DOUBLE PRECISION NOT NULL,
    AskPrice2 DOUBLE PRECISION NOT NULL,
    AskVolume2 DOUBLE PRECISION NOT NULL,
    BidPrice3 DOUBLE PRECISION NOT NULL,
    BidVolume3 DOUBLE PRECISION NOT NULL,
    AskPrice3 DOUBLE PRECISION NOT NULL,
    AskVolume3 DOUBLE PRECISION NOT NULL,
    BidPrice4 DOUBLE PRECISION NOT NULL,
    BidVolume4 DOUBLE PRECISION NOT NULL,
    AskPrice4 DOUBLE PRECISION NOT NULL,
    AskVolume4 DOUBLE PRECISION NOT NULL,
    BidPrice5 DOUBLE PRECISION NOT NULL,
    BidVolume5 DOUBLE PRECISION NOT NULL,
    AskPrice5 DOUBLE PRECISION NOT NULL,
    AskVolume5 DOUBLE PRECISION NOT NULL,
    AveragePrice DOUBLE PRECISION NOT NULL,
    ActionDay TEXT NOT NULL,
    InstrumentID TEXT NOT NULL,
    ExchangeInstID TEXT NOT NULL,
    BandingUpperPrice DOUBLE PRECISION NOT NULL,
    BandingLowerPrice DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (
        InstrumentID,
        UpdateTime,
        UpdateMillisec
    )
);

CREATE TABLE Instrument (
    -- reserve1 TEXT NOT NULL,
    ExchangeID TEXT NOT NULL,
    InstrumentName TEXT NOT NULL,
    -- reserve2 TEXT NOT NULL,
    -- reserve3 TEXT NOT NULL,
    ProductClass TEXT NOT NULL,
    DeliveryYear INT NOT NULL,
    DeliveryMonth INT NOT NULL,
    MaxMarketOrderVolume INT NOT NULL,
    MinMarketOrderVolume INT NOT NULL,
    MaxLimitOrderVolume INT NOT NULL,
    MinLimitOrderVolume INT NOT NULL,
    VolumeMultiple INT NOT NULL,
    PriceTick DOUBLE PRECISION NOT NULL,
    CreateDate TEXT NOT NULL,
    OpenDate TEXT NOT NULL,
    ExpireDate TEXT NOT NULL,
    StartDelivDate TEXT NOT NULL,
    EndDelivDate TEXT NOT NULL,
    InstLifePhase TEXT NOT NULL,
    IsTrading INT NOT NULL,
    PositionType TEXT NOT NULL,
    PositionDateType TEXT NOT NULL,
    LongMarginRatio DOUBLE PRECISION NOT NULL,
    ShortMarginRatio DOUBLE PRECISION NOT NULL,
    MaxMarginSideAlgorithm TEXT NOT NULL,
    -- reserve4 TEXT NOT NULL,
    StrikePrice DOUBLE PRECISION NOT NULL,
    OptionsType TEXT NOT NULL,
    UnderlyingMultiple DOUBLE PRECISION NOT NULL,
    CombinationType TEXT NOT NULL,
    InstrumentID TEXT NOT NULL,
    ExchangeInstID TEXT NOT NULL,
    ProductID TEXT NOT NULL,
    UnderlyingInstrID TEXT NOT NULL,
    PRIMARY KEY (InstrumentID)
);